### PR TITLE
Update Project.toml

### LINKED ISSUE #530: Bump Setfield dependency to 1.0
Can we bump Setfield to the major release? The 0.8 in Transducers.jl is blocking updates downstream.

### PR DESCRIPTION
**Pull request by juliohm**
Fix #530

### CODE REVIEW

**Comment by juliohm** [comment]
Code coverage is never correct with Julia packages you can ignore it.

@tkf appreciate if you can merge this. There are no changes from 0.8 to 1.0, it is just a new tag as far as I know.

**Comment by juliohm** [comment]
Appreciate if someone can merge this.

**Comment by juliohm** [comment]
ping @tkf

**Comment by giordano** [comment]
Duplicate of #523

**Comment by juliohm** [comment]
Thank you @giordano , is there anyone maintaining Transducers.jl that could please merge this bump in Project.toml? It is a really trivial merge that is holding a bunch of packages downstream.

**Comment by giordano** [comment]
I'm not involved in this project so I don't have more information than you, but judging by https://github.com/orgs/JuliaFolds/people I presume it's at least @tkf and @DilumAluthge.

**Comment by juliohm** [comment]
@DilumAluthge can you help merging that other PR that bumps SetField to 1.0?

**Pull request closed without merging**
